//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Padre_Tutor
    {
        public int ID_Tutor { get; set; }
        public int ID_Estudiante { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Parentesco { get; set; }
        public long Cedula { get; set; }
        public string Direccion { get; set; }
        public string Profesion { get; set; }
        public Nullable<long> Telefono { get; set; }
        public Nullable<long> Celular { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
