//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int ID_Registro { get; set; }
        public int ID_Estudiante { get; set; }
        public string Usuario { get; set; }
        public byte[] Contraseña { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
    }
}
