//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Asignar_Tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asignar_Tarea()
        {
            this.Subir_Tarea = new HashSet<Subir_Tarea>();
        }
    
        public int ID_AsignarTarea { get; set; }
        public int ID_Materia { get; set; }

        [Required(ErrorMessage = "Debe especificar un Título")]
        [Display(Name = "Título")]
        [MaxLength(300)]
        public string Titulo { get; set; }

        [Required(ErrorMessage = "Debe especificar un Contenido")]
        public string Contenido { get; set; }

        public virtual Materias Materias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subir_Tarea> Subir_Tarea { get; set; }
    }
}
