//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignar_Tarea
    {
        public int ID_AsignarTarea { get; set; }
        public int ID_Materia { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
    
        public virtual Materias Materias { get; set; }
    }
}
