//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public int Id { get; set; }
        public int Id_Estudiante { get; set; }
        public int Id_Materia { get; set; }
        public int Id_Profesor { get; set; }
        public decimal Nota { get; set; }
    
        public virtual Materias Materias { get; set; }
        public virtual Profesor Profesor { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
