//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiante()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
            this.Direccion = new HashSet<Direccion>();
            this.Documentos_Estudiantes = new HashSet<Documentos_Estudiantes>();
            this.Padre_Tutor = new HashSet<Padre_Tutor>();
            this.Registro = new HashSet<Registro>();
        }
    
        public int ID_Estudiante { get; set; }
        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(50)]
        [Display(Name = "Primer Nombre")]
        public string Primer_Nombre { get; set; }

        [MaxLength(50)]
        [Display(Name = "Segundo Nombre")]
        public string Segundo_Nombre { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(50)]
        [Display(Name = "Primer Apellido")]
        public string Primer_Apellido { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(50)]
        [Display(Name = "Segundo Apellido")]
        public string Segundo_Apelido { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Este campo es obligatorio")]
        [Display(Name = "Fecha de Nacimiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime FechaNacimiento { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [Range(1, 150)]
        public short Edad { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(50)]
        public string Nacionalidad { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        public string Sexo { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [Display(Name = "Grado que Solicita")]
        public int ID_Grado { get; set; }

        [MaxLength(100)]
        [Display(Name = "Centro Educativo")]
        public string CentroEducativo { get; set; }

        [MaxLength(50)]
        [Display(Name = "Último Grado Cursado")]
        public string GradoSolicita { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(50)]
        [Display(Name = "Distrito Educativo")]
        public string DistritoEducativo { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Direccion> Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documentos_Estudiantes> Documentos_Estudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Padre_Tutor> Padre_Tutor { get; set; }
        public virtual Grado Grado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro> Registro { get; set; }
    }
}
