//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Padre_Tutor
    {
        public int ID_Tutor { get; set; }
        public int ID_Estudiante { get; set; }
        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(100)]
        public string Nombres { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(100)]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        public string Parentesco { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [Display(Name = "Cédula")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{7})[-. ]?([0-9]{1})$", ErrorMessage = "Cédula no válida")]
        public long Cedula { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [Display(Name = "Profesión")]
        [MaxLength(100)]
        public string Profesion { get; set; }

        [Display(Name = "Teléfono")]
        [Required(ErrorMessage = "Este campo es obligatorio")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Teléfono no válido")]
        public Nullable<long> Telefono { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Celularo no válido")]
        public Nullable<long> Celular { get; set; }

        public virtual Estudiante Estudiante { get; set; }
    }
}
