//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
        }
    
        public int ID_Profesor { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [Display(Name = "Grado")]
        public int ID_Grado { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(100)]
        public string Nombres { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [MaxLength(100)]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [Display(Name = "Cédula")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{7})[-. ]?([0-9]{1})$", ErrorMessage = "Cédula no válida")]
        public long Cedula { get; set; }

        [Display(Name = "Título")]
        public byte[] Titulo { get; set; }

        [Display(Name = "Currículum")]
        public byte[] Curriculum { get; set; }

        [Display(Name = "Carta de Aceptación")]
        public byte[] CartaAceptacion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
        public virtual Grado Grado { get; set; }
    }
}
