//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
        }
    
        public int ID_Profesor { get; set; }
        public int ID_Grado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public long Cedula { get; set; }
        public byte[] Titulo { get; set; }
        public byte[] Curriculum { get; set; }
        public byte[] CartaAceptacion { get; set; }
    
        public virtual Grado Grado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
    }
}
