//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesor()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
        }
    
        public int ID_Profesor { get; set; }
        public int ID_Grado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public long Cedula { get; set; }
        public byte[] Titulo { get; set; }
        public byte[] Curriculum { get; set; }
        public byte[] CartaAceptacion { get; set; }
    
        public virtual Grado Grado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
    }
}
