//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subir_Tarea
    {
        public int ID_Tarea { get; set; }
        public Nullable<int> ID_Registro { get; set; }
        public byte[] Tarea { get; set; }
        public Nullable<int> ID_Materia { get; set; }
    
        public virtual Materias Materias { get; set; }
        public virtual Registro Registro { get; set; }
    }
}
